### ISSUE TITLE
not work for me only shows a blank page

### ISSUE THREAD

**Issue by Saudiaco** [latfur1/angularjs-php-mysql-crud#1]
Thank you very much for this script
But unfortunately did not work for me only shows a blank page.
Please address the error and thank you very much.

![33](https://user-images.githubusercontent.com/32238459/30781640-a07b30c6-a12b-11e7-9710-151073f31c83.png)

**Comment by xeph126** [comment]
Actually it works. I've also encountered the error since I replaced the director name to something.
Make sure to replace the base href in index.html and do not forget to clear browser cache.
`<base href="http://localhost/[your directory name]/"> `

Regards,
